# Satellite Pass Tracker Configuration

# Observer location
observer:
  latitude: 37.7749
  longitude: -122.4194
  elevation: 0  # meters above sea level

# Tracking settings
tracking:
  days_ahead: 10
  min_elevation: 10.0  # degrees
  delete_existing: true  # Delete existing events before creating new ones

# Google Calendar settings
calendar:
  calendar_id: "primary"  # Use "primary" or specific calendar ID
  
# List of satellites to track
satellites:
  - name: "ISS"
    url: "https://celestrak.org/NORAD/elements/gp.php?CATNR=25544&FORMAT=tle"
  
  - name: "NOAA-18"
    url: "https://celestrak.org/NORAD/elements/gp.php?CATNR=28654&FORMAT=tle"
  
  - name: "NOAA-19"
    url: "https://celestrak.org/NORAD/elements/gp.php?CATNR=33591&FORMAT=tle"
  
  # Add more satellites as needed
  # - name: "Satellite Name"
  #   url: "https://example.com/tle_url"