name: Track Satellite Passes

on:
  schedule:
    # Run daily at 00:00 UTC
    - cron: '0 0 * * *'
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  track-passes:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyyaml  # For config file
    
    - name: Create credentials file
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
        echo "$GOOGLE_CREDENTIALS" > credentials.json
    
    - name: Create token file
      env:
        GOOGLE_TOKEN: ${{ secrets.GOOGLE_TOKEN }}
      run: |
        echo "$GOOGLE_TOKEN" > token.json
    
    - name: Run satellite tracker
      run: |
        python satellite_batch_tracker.py
    
    - name: Upload logs as artifact
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: tracking-logs
        path: |
          *.log
        retention-days: 7